### ISSUE TITLE
Clustering denoised data and OTUs

### ISSUE THREAD

**Issue by tenguzame** [swo/dbotu3#14]
Greetings,
I have two different datasets, one created through 454 sequencing and one through Illumina sequencing. I have clustered 454 sequences into OTUs and denoised Illumina data to obtain ASVs, and I need to compare them as a single dataset.
In order to investigate whether the same organisms could be found in both datasets (i.e. the same OTU/ASV across samples in the two datasets), I was planning to use the dbOTU3 implementation. Would this be an accurate way to use your approach?
Best regards

**Comment by cduvallet** [comment]
Hi @tenguzame,

Thanks for writing, glad you found the tool and are looking to use it! A couple of things:

1. This repo is no longer maintained. You should use the code in the https://github.com/almlab/dbotu3 version. That's also where you should raise any future issues. 

2. Your message isn't quite a bug but rather a user question. Unfortunately GitHub doesn't really provide a space to answer user questions (raising issues is more about finding bugs or requesting improvements to the code). Luckily, the folks over at QIIME 2 have curated a great community of microbiome researchers in an active user forum: https://forum.qiime2.org/ . If you re-post this question there and tag me in it (my forum username is cduvallet), I'll answer it there! This way, the whole community can benefit :)

Also note that if you are a QIIME 2 user, there is also a plugin for dbotu3 available.
