### ISSUE TITLE
Log file gets huge

### ISSUE THREAD

**Issue by spacocha** [swo/dbotu3#3]
The log file gets huge if it's verbose, but sometimes you want to track the progress without all the extra information. Can you change the verbose option so that in verbose it spews all of the information you have there, but when verbose is off, it still creates a log containing something like  the values for the variable parameters, maybe which version of dbotu3 and which sequences it has worked through? I would suggest that the default is verbose off and change to on if all the additional information is needed.

**Comment by swo** [comment]
Interesting idea. I mostly made the log file as a way to debug the algorithm, but I suppose that most users wouldn't use it for that!

It seems like a log file could do a few things:

- help with debugging (which should maybe be a separate debug log)
- give information about the current state of the run (e.g., some info like "I'm on sequence 23 of 100")
- give information about the decisions made by the run up to that point (i.e., sequences 1, 2, and 5 have been made into their own OTUs, sequence 3 was merged into OTU 1, etc.)
- give information about the specifics of the run (e.g., dbOTU version, parameter values, input/output files)

Anything I've missed?

**Comment by spacocha** [comment]
No, I think that's about all I'd be interested in. Related to the other comment, if it could include just enough information to restart if it dies, that would be ideal (but no more). Then you can turn debug on or off. Although I could imagine you could turn the log off too, but that would be at your own peril. I like which sequence it is (not just 23 of 100) just because then you can see if it gets tripped up at a particular sequence you can go there and check it out, but that's not necessary.

**Comment by swo** [comment]
This should be dealt with by the current commit. Check out the new command-line interface (which has separate `--log` and `--debug` options) and the type of output (in `data/output`). The `log.txt` file has a header with information about the run and then just information about what got merged into what. It's not on PyPi yet.
