### ISSUE TITLE
Output file is empty (problem with pandas/python)

### ISSUE THREAD

**Issue by nailabc** [swo/dbotu3#4]
I tried to run dbotu.py installed with python 3.6.1 in a Mac OS and it seems that there is a problem with pandas. I tried to update pandas and create a virtual environment with conda, where I installed dbotu with python3 again, but I get again the same error (see below).
% dbotu.py counts.txt seq.fa --output otu.txt
Traceback (most recent call last):
  File "/usr/local/bin/dbotu.py", line 396, in <module>
    call_otus(args.table, args.fasta, args.output, args.dist, args.abund, args.pval, log=args.log, membership=args.membership, debug=args.debug)
  File "/usr/local/bin/dbotu.py", line 346, in call_otus
    seq_table = read_sequence_table(seq_table_fh)
  File "/usr/local/bin/dbotu.py", line 313, in read_sequence_table
    if type(df.index) is pd.indexes.multi.MultiIndex:
AttributeError: module 'pandas' has no attribute 'indexes'

**Comment by swo** [comment]
Thanks for using (or trying to use) dbOTU! I think I fixed that problem with this pull request #5. If you're able to test it out before I submit it to the main branch, let me know. If not, I'll probably just merge it anyway.

**Comment by nailabc** [comment]
It worked! Thanks a lot!

**Comment by swo** [comment]
Great, thanks for pointing out this bug!
