### ISSUE TITLE
Output fasta file of OTU represenatives

### ISSUE THREAD

**Issue by spacocha** [swo/dbotu3#6]
A user would like to have the fasta file of OTU representatives as one of the outputs. This allows them to go directly into something like the chimera checking programs without having to filter with another program's tools. There are other tools and programs that might do this kind of thing, but it is a common step users will need to do, so that would be nice to provide for people.

**Comment by swo** [comment]
I feel conflicted about this. I know people like one-stop-shops, but I also don't like bloating the main program with tools that aren't the core function of the program. For example, Qiime's `filter_fasta.py` does, I think, exactly this requested functionality. Thoughts?

**Comment by spacocha** [comment]
True, other tools are available and it does add bulk, but for something that's so common (and something I provided with the original code), I think this one addition would be a reasonable amount of bulk to add. Using other available tools like QIIME could be a challenge, or more likely an inconvenience, for the user to run and we should make it as easy for them to use as possible. That's my two cents.

**Comment by swo** [comment]
Sounds fair. I've put a new `dbotu_rep_seqs.py` script on the "restart" branch. If that (and the restart script) meets your needs, let me know and I'll merge them into the main branch.

**Comment by swo** [comment]
I added this script to the main repo in the latest commit.
