### ISSUE TITLE
Script error when log file not specified

### ISSUE THREAD

**Issue by Starnite** [swo/dbotu3#7]
Command: dbotu.py counts.txt seqs.fasta -o my-otu-table.txt 

```
Traceback (most recent call last):
  File "/Users/vivzhong/anaconda/bin/dbotu.py", line 397, in <module>
    call_otus(args.table, args.fasta, args.output, args.dist, args.abund, args.pval, log=args.log, membership=args.membership, debug=args.debug)
  File "/Users/vivzhong/anaconda/bin/dbotu.py", line 363, in call_otus
    caller._print_progress_log('progress_log_output_filename', os.path.realpath(log.name))
AttributeError: 'NoneType' object has no attribute 'name'
```

Error can be avoided by commenting out the problematic line (363).

**Comment by swo** [comment]
Thanks! I fixed this with a [new commit](https://github.com/swo/dbotu3/commit/d52fa8e49da9ab19b5c7b985570559d8c97279b7) on the `restart` branch, which I expect will be incorporated into the main branch very soon.
